### ISSUE TITLE
Checklist para práticas de Git

### ISSUE THREAD

**Issue by CarlaMSilva** [CarlaMSilva/GCMS-Carla-silva#2]
Checklist para práticas de Git
- [ ] Instalar Git localmente
- [ ] Criar projeto local
- [ ] Criar repositório local e realizar commits
- [ ] Subir alterações para o repositório remoto
- [ ] Fazer alterações no repositório da turma

@ramidedantas , poderia revisar este checklist para as próximas práticas?

**Comment by ramidedantas** [comment]
@CarlaMSilva revise a formatação para ficar com checkboxes, como abaixo:
- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

**Comment by CarlaMSilva** [comment]
Feito!
